/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOTravelling;

import static java.awt.SystemColor.text;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author A
 */
public class OOTravels extends javax.swing.JFrame {
    
    double Gross;
    cFlight cost = new cFlight();

    /**
     * Creates new form OOTravels
     */
    public OOTravels() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel48 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtpostcode = new javax.swing.JTextField();
        txttelephone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo_destination = new javax.swing.JComboBox<>();
        combo_accomodation = new javax.swing.JComboBox<>();
        boxmedi = new javax.swing.JCheckBox();
        boxtravelling_insurance = new javax.swing.JCheckBox();
        boxair_miles = new javax.swing.JCheckBox();
        boxextra_luggage = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        combo_departure = new javax.swing.JComboBox<>();
        txtreturn = new javax.swing.JTextField();
        rbtnstandard = new javax.swing.JRadioButton();
        rbtneconomy = new javax.swing.JRadioButton();
        rbtnsingle = new javax.swing.JRadioButton();
        txtstandard = new javax.swing.JTextField();
        txteconomy = new javax.swing.JTextField();
        txtsingle = new javax.swing.JTextField();
        rbtnreturn = new javax.swing.JRadioButton();
        txtsubtotal = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttax = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        btnreceipt = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtreceipt = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        rbtnfirstclass = new javax.swing.JRadioButton();
        txtfirstclass = new javax.swing.JTextField();
        boxairporttax1 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 470));
        setPreferredSize(new java.awt.Dimension(1300, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setBackground(new java.awt.Color(0, 51, 204));
        jLabel48.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Travel Management System");
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 8));
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1257, 84));

        txtfirstname.setBackground(new java.awt.Color(204, 204, 204));
        txtfirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfirstname.setText(" ");
        txtfirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 126, 211, -1));

        txtlastname.setBackground(new java.awt.Color(204, 204, 204));
        txtlastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtlastname.setText(" ");
        txtlastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 160, 211, -1));

        txtaddress.setBackground(new java.awt.Color(204, 204, 204));
        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtaddress.setText(" ");
        txtaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 194, 211, -1));

        txtpostcode.setBackground(new java.awt.Color(204, 204, 204));
        txtpostcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtpostcode.setText(" ");
        txtpostcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtpostcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 225, 211, -1));

        txttelephone.setBackground(new java.awt.Color(204, 204, 204));
        txttelephone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttelephone.setText(" ");
        txttelephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txttelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 257, 211, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Firstname");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 128, -1, -1));

        txtemail.setBackground(new java.awt.Color(204, 204, 204));
        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.setText(" ");
        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 293, 211, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Lastname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 163, -1, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 196, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Post Code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 227, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telephone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 259, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 295, -1, -1));

        combo_destination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Sylhet Airport", "Chittagong Airport", "India Airport", "Shanghai Airport", "Toronto Airport", "Tokyo Airport", "Jakarta Airport", "Moscow Airport", "New York Airport", "Canada Airport", "Brazil Airport", "Argentina Airport", "Berlin Airport", "Maldives Airport", "Sri Lanka Airport", "Nepal Airport", "Bhutan Airoprt", "Taiwan Airport", "Egypt Airport" }));
        combo_destination.setEnabled(false);
        combo_destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_destinationActionPerformed(evt);
            }
        });
        getContentPane().add(combo_destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 167, 231, -1));

        combo_accomodation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_accomodation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        getContentPane().add(combo_accomodation, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 211, 231, -1));

        boxmedi.setBackground(new java.awt.Color(51, 153, 255));
        boxmedi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boxmedi.setText("Medical Requirement");
        getContentPane().add(boxmedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        boxtravelling_insurance.setBackground(new java.awt.Color(51, 153, 255));
        boxtravelling_insurance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boxtravelling_insurance.setText("Travelling Insurance");
        getContentPane().add(boxtravelling_insurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        boxair_miles.setBackground(new java.awt.Color(51, 153, 255));
        boxair_miles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boxair_miles.setText("Air Miles Over 20000");
        boxair_miles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxair_milesActionPerformed(evt);
            }
        });
        getContentPane().add(boxair_miles, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        boxextra_luggage.setBackground(new java.awt.Color(51, 153, 255));
        boxextra_luggage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boxextra_luggage.setText("Extra Luggage");
        getContentPane().add(boxextra_luggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Departure");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 129, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Destination");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Accommodation");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 211, -1, -1));

        combo_departure.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka Airport" }));
        getContentPane().add(combo_departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 126, 231, -1));

        txtreturn.setEditable(false);
        txtreturn.setBackground(java.awt.Color.lightGray);
        txtreturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtreturn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtreturn.setText("0");
        txtreturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreturnActionPerformed(evt);
            }
        });
        getContentPane().add(txtreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 90, -1));

        rbtnstandard.setBackground(new java.awt.Color(51, 153, 255));
        rbtnstandard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnstandard.setText("Standard");
        rbtnstandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnstandardActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnstandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        rbtneconomy.setBackground(new java.awt.Color(51, 153, 255));
        rbtneconomy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtneconomy.setText("Economy");
        rbtneconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtneconomyActionPerformed(evt);
            }
        });
        getContentPane().add(rbtneconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        rbtnsingle.setBackground(new java.awt.Color(51, 153, 255));
        rbtnsingle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnsingle.setText("Single");
        rbtnsingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnsingleActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 360, -1, -1));

        txtstandard.setEditable(false);
        txtstandard.setBackground(java.awt.Color.lightGray);
        txtstandard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtstandard.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtstandard.setText("0");
        txtstandard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtstandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstandardActionPerformed(evt);
            }
        });
        getContentPane().add(txtstandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 90, -1));

        txteconomy.setEditable(false);
        txteconomy.setBackground(java.awt.Color.lightGray);
        txteconomy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txteconomy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txteconomy.setText("0");
        txteconomy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txteconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 90, -1));

        txtsingle.setEditable(false);
        txtsingle.setBackground(java.awt.Color.lightGray);
        txtsingle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsingle.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsingle.setText("0");
        txtsingle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtsingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsingleActionPerformed(evt);
            }
        });
        getContentPane().add(txtsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 90, -1));

        rbtnreturn.setBackground(new java.awt.Color(51, 153, 255));
        rbtnreturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnreturn.setText("Including Return Expense");
        rbtnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        txtsubtotal.setEditable(false);
        txtsubtotal.setBackground(java.awt.Color.lightGray);
        txtsubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsubtotal.setText("0");
        txtsubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 420, 90, -1));

        txttotal.setEditable(false);
        txttotal.setBackground(java.awt.Color.lightGray);
        txttotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotal.setText("0");
        txttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 80, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tax");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Subtotal");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, -1, -1));

        txttax.setEditable(false);
        txttax.setBackground(java.awt.Color.lightGray);
        txttax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttax.setText("0");
        txttax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 360, 90, -1));

        btnreset.setBackground(new java.awt.Color(0, 0, 0));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 470, -1, 30));

        btntotal.setBackground(new java.awt.Color(0, 0, 0));
        btntotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntotal.setForeground(new java.awt.Color(255, 255, 255));
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });
        getContentPane().add(btntotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, 30));

        btnreceipt.setBackground(new java.awt.Color(0, 0, 0));
        btnreceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnreceipt.setText("Receipt");
        btnreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceiptActionPerformed(evt);
            }
        });
        getContentPane().add(btnreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, -1, 30));

        btnexit.setBackground(new java.awt.Color(0, 0, 0));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 470, -1, 30));

        txtreceipt.setEditable(false);
        txtreceipt.setBackground(java.awt.Color.lightGray);
        txtreceipt.setColumns(20);
        txtreceipt.setRows(5);
        txtreceipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtreceipt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 271, 319));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Receipt");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 110, -1, -1));

        rbtnfirstclass.setBackground(new java.awt.Color(51, 153, 255));
        rbtnfirstclass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnfirstclass.setText("First Class");
        rbtnfirstclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnfirstclassActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnfirstclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        txtfirstclass.setEditable(false);
        txtfirstclass.setBackground(java.awt.Color.lightGray);
        txtfirstclass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfirstclass.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtfirstclass.setText("0");
        txtfirstclass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(txtfirstclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 90, -1));

        boxairporttax1.setBackground(new java.awt.Color(51, 153, 255));
        boxairporttax1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boxairporttax1.setText("Airport Tax");
        boxairporttax1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxairporttax1ActionPerformed(evt);
            }
        });
        getContentPane().add(boxairporttax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jLabel15.setBackground(java.awt.Color.lightGray);
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOTravelling/image-2018-12-27.jpg"))); // NOI18N
        jLabel15.setText(" ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_destinationActionPerformed
        cFlight cost = new cFlight();
        if((combo_destination.getSelectedItem().equals("Sylhet Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sSylhet_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Chittagong Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sChittagong_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("India Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sIndia_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Shanghai Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sShanghai_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Toronto Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sToronto_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Tokyo Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sTokyo_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Jakarta Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sJakarta_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Moscow Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sMoscow_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("New York Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sNew_York_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Canada Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sCanada_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Brazil Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sBrazil_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Argentina Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sArgentina_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Berlin Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sBerlin_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Maldives Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sMaldives_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Sri Lanka Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sSri_Lanka_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Nepal Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sNepal_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Bhutan Airoprt")) && rbtnstandard.isSelected())
        {
            Gross=cost.sBhutan_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Taiwan Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sTaiwan_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Egypt Airport")) && rbtnstandard.isSelected())
        {
            Gross=cost.sEgypt_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtstandard.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        //=================================================================================
        if((combo_destination.getSelectedItem().equals("Sylhet Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eSylhet_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Chittagong Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eChittagong_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("India Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eIndia_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Shanghai Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eShanghai_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Toronto Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eToronto_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Tokyo Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eTokyo_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Jakarta Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eJakarta_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Moscow Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eMoscow_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("New York Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eNew_York_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Canada Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eCanada_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Brazil Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eBrazil_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Argentina Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eArgentina_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Berlin Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eBerlin_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Maldives Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eMaldives_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Sri Lanka Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eSri_Lanka_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Nepal Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eNepal_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Bhutan Airoprt")) && rbtneconomy.isSelected())
        {
            Gross=cost.eBhutan_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Taiwan Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eTaiwan_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Egypt Airport")) && rbtneconomy.isSelected())
        {
            Gross=cost.eEgypt_Airport;
            String Cost = String.format("$%.2f", Gross);
            txteconomy.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        //========================================================
        if((combo_destination.getSelectedItem().equals("Sylhet Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fSylhet_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Chittagong Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fChittagong_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("India Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fIndia_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Shanghai Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fShanghai_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Toronto Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fToronto_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Tokyo Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fTokyo_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Jakarta Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fJakarta_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Moscow Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fMoscow_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("New York Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fNew_York_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Canada Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fCanada_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Brazil Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fBrazil_Airport;
            String Cost= String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Argentina Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fArgentina_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Berlin Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fBerlin_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Maldives Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fMaldives_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Sri Lanka Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fSri_Lanka_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Nepal Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fNepal_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Bhutan Airoprt")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fBhutan_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Taiwan Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fTaiwan_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
        if((combo_destination.getSelectedItem().equals("Egypt Airport")) && rbtnfirstclass.isSelected())
        {
            Gross=cost.fEgypt_Airport;
            String Cost = String.format("$%.2f", Gross);
            txtfirstclass.setText(Cost);
            txtsingle.setText(Cost);
            rbtnsingle.setSelected(true);
        }
    }//GEN-LAST:event_combo_destinationActionPerformed

    private void txtreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreturnActionPerformed

    private void rbtnstandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnstandardActionPerformed
        if(rbtnstandard.isSelected()==true)
        {
            combo_destination.setEnabled(true);
            rbtneconomy.setEnabled(false);
            rbtnfirstclass.setEnabled(false);
            txteconomy.setText("0");
            txtfirstclass.setText("0");
            txtsingle.setText("0");
            txtreturn.setText("0");
        }
        else
        {
            rbtneconomy.setEnabled(true);
            rbtnfirstclass.setEnabled(true);
        }
        if(rbtnstandard.isSelected()==false)
        {
            combo_destination.setSelectedItem("None");
            combo_destination.setEnabled(false);
            txtstandard.setText("0");
        }
    }//GEN-LAST:event_rbtnstandardActionPerformed

    private void rbtneconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtneconomyActionPerformed
        if(rbtneconomy.isSelected()==true)
        {
            combo_destination.setEnabled(true);
            rbtnstandard.setEnabled(false);
            rbtnfirstclass.setEnabled(false);
            txtstandard.setText("0");
            txtfirstclass.setText("0");
            txtsingle.setText("0");
            txtreturn.setText("0");
        }
        else
        {
            rbtnstandard.setEnabled(true);
            rbtnfirstclass.setEnabled(true);
        }
        if(rbtneconomy.isSelected()==false)
        {
            combo_destination.setSelectedItem("None");
            combo_destination.setEnabled(false);
            txteconomy.setText("0");
        }
    }//GEN-LAST:event_rbtneconomyActionPerformed

    private void rbtnsingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnsingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnsingleActionPerformed

    private void txtstandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstandardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstandardActionPerformed

    private void txtsingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsingleActionPerformed

    private void rbtnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnreturnActionPerformed

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtfirstname.setText(null);
        txttax.setText("0");
        txtsubtotal.setText("0");
        txttotal.setText("0");
        txtlastname.setText(null);
        txtaddress.setText(null);
        txttelephone.setText(null);
        txtemail.setText(null);
        txtpostcode.setText(null);
        txtreceipt.setText(null);
        txtsingle.setText("0");
        txtsingle.setText("0");
        txtstandard.setText("0");
        txtreturn.setText("0");
        txteconomy.setText("0");
        txtfirstclass.setText("0");
        combo_departure.setSelectedItem("None");
        combo_destination.setSelectedItem("None");
        combo_destination.setEnabled(false);
        combo_accomodation.setSelectedItem("None");
        rbtnstandard.setSelected(false);
        rbtneconomy.setSelected(false);
        rbtnfirstclass.setSelected(false);
        boxair_miles.setSelected(false);
        boxmedi.setSelected(false);
        boxmedi.setSelected(false);
        boxtravelling_insurance.setSelected(false);
        boxextra_luggage.setSelected(false);
        rbtnsingle.setSelected(false);
        rbtnreturn.setSelected(false);
        rbtnstandard.setEnabled(true);
        rbtneconomy.setEnabled(true);
        rbtnfirstclass.setEnabled(true);
        rbtnfirstclass.setEnabled(true);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed

        cCostTax iTax = new cCostTax();
        double iTaxes,subtotal,total;

        if(rbtnreturn.isSelected())
        {
            subtotal=Gross*2;
            String isubtotal = String.format("$%.2f",subtotal);
            txtsubtotal.setText(isubtotal);
            iTaxes = iTax.cFindTax(subtotal);
            String Tax = String.format("$%.2f",iTaxes);
            txttax.setText(Tax);
            String iTotal = String.format("$%.2f",subtotal+iTaxes);
            txttotal.setText(iTotal);
            txtreturn.setText(isubtotal);
        }
        else
        {
            subtotal=Gross;
            String isubtotal = String.format("$%.2f",subtotal);
            txtsubtotal.setText(isubtotal);
            iTaxes = iTax.cFindTax(subtotal);
            String Tax = String.format("$%.2f",iTaxes);
            txttax.setText(Tax);
            String iTotal = String.format("$%.2f",subtotal+ iTaxes);
            txttotal.setText(iTotal);

        }
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceiptActionPerformed
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:MM:SS");
        String iTime = (tTime.format(timer.getTime()));

        SimpleDateFormat Tdate = new SimpleDateFormat("dd:MM:YYYY");
        String iDate = (Tdate.format(timer.getTime()));

        int num1;
        String ref="";
        num1 = 1325+(int)(Math.random()*4238);
        ref+=num1 + 1325;

        //================================================================
        String Firstname = (txtfirstname.getText());
        String Lastname = (txtlastname.getText());
        String address = (txtaddress.getText());
        String postcode = (txtpostcode.getText());
        String telephone = (txttelephone.getText());
        String email = (txtemail.getText());
        String rTax = (txttax.getText());
        String rSubtotal = (txtsubtotal.getText());
        String rTotal = (txttotal.getText());

        txtreceipt.append("\t  Travel Management System:\n\n"
            +"  Ref:\t\t"+ref
            +"\n------------------------------------------------------"
            +"\n  Firstname:\t\t"+Firstname
            +"\n  Lastname:\t\t"+Lastname
            +"\n  Address:\t\t"+address
            +"\n  Postcode:\t\t"+postcode
            +"\n  Telephone:\t\t"+telephone
            +"\n  Email:\t\t"+email
            +"\n  Tax:\t\t"+rTax
            +"\n  Subtotal:\t\t"+rSubtotal
            +"\n  Total:\t\t"+rTotal
            +"\n-------------------------------------------------------"
            +"\n  Date:"+iDate+"\tTime:"+iTime
            +"\n\n  Thanks for using \n\tTravel Management System");
    }//GEN-LAST:event_btnreceiptActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        cQuit cExit = new cQuit();
        cExit.quit();
    }//GEN-LAST:event_btnexitActionPerformed

    private void rbtnfirstclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnfirstclassActionPerformed
        if(rbtnfirstclass.isSelected()==true)
        {
            combo_destination.setEnabled(true);
            rbtneconomy.setEnabled(false);
            rbtnstandard.setEnabled(false);
            txteconomy.setText("0");
            txtstandard.setText("0");
            txtsingle.setText("0");
            txtreturn.setText("0");
        }
        else
        {
            rbtneconomy.setEnabled(true);
            rbtnstandard.setEnabled(true);
        }
        if(rbtnfirstclass.isSelected()==false)
        {
            combo_destination.setSelectedItem("None");
            combo_destination.setEnabled(false);
            txtfirstclass.setText("0");
        }
    }//GEN-LAST:event_rbtnfirstclassActionPerformed

    private void boxairporttax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxairporttax1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxairporttax1ActionPerformed

    private void boxair_milesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxair_milesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxair_milesActionPerformed

    /**}
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Travel_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxair_miles;
    private javax.swing.JCheckBox boxairporttax1;
    private javax.swing.JCheckBox boxextra_luggage;
    private javax.swing.JCheckBox boxmedi;
    private javax.swing.JCheckBox boxtravelling_insurance;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnreceipt;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> combo_accomodation;
    private javax.swing.JComboBox<String> combo_departure;
    private javax.swing.JComboBox<String> combo_destination;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtneconomy;
    private javax.swing.JRadioButton rbtnfirstclass;
    private javax.swing.JRadioButton rbtnreturn;
    private javax.swing.JRadioButton rbtnsingle;
    private javax.swing.JRadioButton rbtnstandard;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txteconomy;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstclass;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtpostcode;
    private javax.swing.JTextArea txtreceipt;
    private javax.swing.JTextField txtreturn;
    private javax.swing.JTextField txtsingle;
    private javax.swing.JTextField txtstandard;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttax;
    private javax.swing.JTextField txttelephone;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
